"""
Django settings for social_automation project.

Generated by 'django-admin startproject' using Django 5.2.11.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from datetime import timedelta
from pathlib import Path

from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
load_dotenv(BASE_DIR / ".env")

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("DJANGO_SECRET_KEY")


# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv("DJANGO_DEBUG", "1") == "1"




def _get_allowed_hosts():
    if not DEBUG:
        return [h.strip() for h in (os.getenv("ALLOWED_HOSTS", "") or "").split(",") if h.strip()]
    hosts = ["localhost", "127.0.0.1"]
    # Permite acesso pela rede quando FRONTEND_URL aponta para IP (ex: http://192.168.1.100:5173)
    try:
        from urllib.parse import urlparse
        frontend = (os.getenv("FRONTEND_URL") or "").strip()
        if frontend:
            parsed = urlparse(frontend)
            if parsed.hostname and parsed.hostname not in hosts:
                hosts.append(parsed.hostname)
    except Exception:
        pass
    return hosts


ALLOWED_HOSTS = _get_allowed_hosts()


# Application definition

INSTALLED_APPS = [
    "corsheaders",
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    "rest_framework",
    "rest_framework_simplejwt",
    "django_celery_results",
    "apps.brands",
    "apps.mediahub",
    "apps.cuts",
    "apps.jobs",
    "apps.api",
    "apps.auto_cuts",
    "apps.social",
]

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'social_automation.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'social_automation.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases
# Use PostgreSQL quando DATABASE_URL estiver definido (recomendado para Celery multi-worker)
# Ex: postgresql://user:password@host:5432/dbname

_database_url = os.getenv("DATABASE_URL", "").strip()
if _database_url and "postgres" in _database_url.split("://")[0].lower():
    from urllib.parse import urlparse
    # postgres:// e postgresql:// são equivalentes; psycopg2 aceita ambos
    _u = _database_url.replace("postgres://", "postgresql://", 1)
    _p = urlparse(_u)
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.postgresql",
            "NAME": _p.path.lstrip("/").split("?")[0] or "postgres",
            "USER": _p.username or "postgres",
            "PASSWORD": _p.password or "",
            "HOST": _p.hostname or "localhost",
            "PORT": str(_p.port or 5432),
            "CONN_MAX_AGE": 60,
            "OPTIONS": {"connect_timeout": 10},
        }
    }
else:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = os.getenv("LANGUAGE_CODE", "pt-br")

TIME_ZONE = os.getenv("TIME_ZONE", "America/Sao_Paulo")

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

_media = os.getenv("MEDIA_ROOT", "storage/media")
MEDIA_ROOT = Path(_media) if Path(_media).is_absolute() else BASE_DIR / _media
MEDIA_URL = "/media/"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# Cache (OAuth pendente, etc.)
CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
        "OPTIONS": {"MAX_ENTRIES": 100},
    }
}
# Se tiver Redis: pip install django-redis e use "django_redis.cache.RedisCache"

# Celery
CELERY_BROKER_URL = os.getenv("CELERY_BROKER_URL", "redis://127.0.0.1:6379/0")
CELERY_RESULT_BACKEND = os.getenv("CELERY_RESULT_BACKEND", "django-db")
CELERY_ACCEPT_CONTENT = ["json"]
CELERY_TASK_SERIALIZER = "json"
CELERY_RESULT_SERIALIZER = "json"
CELERY_TIMEZONE = os.getenv("CELERY_TIMEZONE", TIME_ZONE)
# Para alinhar scheduler/logs ao fuso local quando desejado.
CELERY_ENABLE_UTC = os.getenv("CELERY_ENABLE_UTC", "0").lower() in ("1", "true", "yes")
# CELERY_EAGER=1: executa tasks no mesmo processo (sem Redis). Útil para dev sem Docker.
CELERY_TASK_ALWAYS_EAGER = os.getenv("CELERY_EAGER", "").lower() in ("1", "true", "yes")
CELERY_TASK_DEFAULT_QUEUE = "processing"
CELERY_TASK_ROUTES = {
    # Fila dedicada para publicação/agendamento (não deve ficar bloqueada por transcrição/render)
    "apps.social.tasks.check_scheduled_posts_task": {"queue": "publish"},
    "apps.social.tasks.process_brand_posting_queue_task": {"queue": "publish"},
    "apps.social.tasks.generate_daily_factory_schedules_task": {"queue": "publish"},
    "apps.social.tasks.post_to_platforms_task": {"queue": "publish"},
    "apps.social.tasks.reconcile_youtube_schedules_task": {"queue": "publish"},
    "apps.social.tasks.upload_thumbnails_after_batch_task": {"queue": "publish"},
    "apps.social.tasks.cleanup_posted_media_task": {"queue": "processing"},
    # Processamento pesado fica na fila padrão de processamento
    "apps.auto_cuts.tasks.analyze_auto_cuts_task": {"queue": "processing"},
    "apps.auto_cuts.tasks.finalizar_auto_cut_task": {"queue": "processing"},
    "apps.jobs.tasks.process_job": {"queue": "processing"},
    "apps.jobs.tasks.generate_subtitles_task": {"queue": "processing"},
    "apps.jobs.tasks.burn_subtitles_task": {"queue": "processing"},
}


# FFmpeg
FFMPEG_BIN = os.getenv("FFMPEG_BIN", "ffmpeg")
FFPROBE_BIN = os.getenv("FFPROBE_BIN", "ffprobe")
# libx264 (CPU): CRF menor = melhor qualidade (ficheiro maior); preset mais lento = melhor compressão (mais tempo).
FFMPEG_LIBX264_CRF = int(os.getenv("FFMPEG_LIBX264_CRF", "20"))
FFMPEG_LIBX264_PRESET = os.getenv("FFMPEG_LIBX264_PRESET", "veryfast")
# Queima de legendas (subtitles filter): omissão = mesmo CRF/preset do pipeline; evita defaults do libx264.
FFMPEG_LIBX264_BURN_CRF = int(os.getenv("FFMPEG_LIBX264_BURN_CRF", str(FFMPEG_LIBX264_CRF)))
FFMPEG_LIBX264_BURN_PRESET = os.getenv("FFMPEG_LIBX264_BURN_PRESET", FFMPEG_LIBX264_PRESET)
# Overlay lateral em vídeo longo: passo sensível a artefactos — padrão mais pesado (slow + CRF 16).
FFMPEG_LIBX264_OVERLAY_LONG_CRF = int(os.getenv("FFMPEG_LIBX264_OVERLAY_LONG_CRF", "16"))
FFMPEG_LIBX264_OVERLAY_LONG_PRESET = os.getenv("FFMPEG_LIBX264_OVERLAY_LONG_PRESET", "slow")

# REST Framework
REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework_simplejwt.authentication.JWTAuthentication",
        "rest_framework.authentication.SessionAuthentication",
    ],
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticated",
    ],
}

# Simple JWT - token válido por 1 dia
SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(days=1),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=7),
}

# CORS - React em desenvolvimento roda em localhost:5173
# Para acesso de outro PC na rede: defina FRONTEND_URL=http://SEU_IP:5173 no .env
_cors_origins = ["http://localhost:5173", "http://127.0.0.1:5173"]
_frontend_url = (os.getenv("FRONTEND_URL") or "").strip().rstrip("/")
if _frontend_url and _frontend_url not in _cors_origins:
    _cors_origins.append(_frontend_url)
CORS_ALLOWED_ORIGINS = _cors_origins

# Reduz ruído no Celery: libs Google (file_cache, Refreshing credentials) em WARNING
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "loggers": {
        "google": {"level": "WARNING"},
        "google.auth": {"level": "WARNING"},
        "googleapiclient": {"level": "WARNING"},
    },
}
