"""
Django settings for social_automation project.

Generated by 'django-admin startproject' using Django 5.2.11.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from datetime import timedelta
from pathlib import Path

from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
load_dotenv(BASE_DIR / ".env")

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("DJANGO_SECRET_KEY")


# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv("DJANGO_DEBUG", "1") == "1"




def _get_allowed_hosts():
    if not DEBUG:
        return [h.strip() for h in (os.getenv("ALLOWED_HOSTS", "") or "").split(",") if h.strip()]
    hosts = ["localhost", "127.0.0.1", "web"]
    # Allow LAN access when FRONTEND_URL points to an IP (e.g. http://192.168.1.100:5173)
    try:
        from urllib.parse import urlparse
        frontend = (os.getenv("FRONTEND_URL") or "").strip()
        if frontend:
            parsed = urlparse(frontend)
            if parsed.hostname and parsed.hostname not in hosts:
                hosts.append(parsed.hostname)
    except Exception:
        pass
    return hosts


ALLOWED_HOSTS = _get_allowed_hosts()


# Application definition

INSTALLED_APPS = [
    "corsheaders",
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    "rest_framework",
    "rest_framework_simplejwt",
    "django_celery_results",
    "apps.brands",
    "apps.mediahub",
    "apps.cuts",
    "apps.jobs",
    "apps.api",
    "apps.auto_cuts",
    "apps.multiple_creator",
    "apps.social",
]

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'social_automation.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'social_automation.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases
# Use PostgreSQL when DATABASE_URL is set (recommended for multi-worker Celery)
# e.g. postgresql://user:password@host:5432/dbname

_database_url = os.getenv("DATABASE_URL", "").strip()
if _database_url and "postgres" in _database_url.split("://")[0].lower():
    from urllib.parse import urlparse
    # postgres:// and postgresql:// are equivalent; psycopg2 accepts both
    _u = _database_url.replace("postgres://", "postgresql://", 1)
    _p = urlparse(_u)
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.postgresql",
            "NAME": _p.path.lstrip("/").split("?")[0] or "postgres",
            "USER": _p.username or "postgres",
            "PASSWORD": _p.password or "",
            "HOST": _p.hostname or "localhost",
            "PORT": str(_p.port or 5432),
            "CONN_MAX_AGE": 60,
            "OPTIONS": {"connect_timeout": 10},
        }
    }
else:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = os.getenv("LANGUAGE_CODE", "en-us")

TIME_ZONE = os.getenv("TIME_ZONE", "America/Sao_Paulo")

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

_media = os.getenv("MEDIA_ROOT", "storage/media")
MEDIA_ROOT = Path(_media) if Path(_media).is_absolute() else BASE_DIR / _media
MEDIA_URL = "/media/"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# Cache (OAuth state, etc.)
CACHE_TIMEOUT = int(os.getenv("CACHE_TIMEOUT", "300"))

if DEBUG:
    CACHES = {
        "default": {
            "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
            "OPTIONS": {"MAX_ENTRIES": 100},
            "TIMEOUT": CACHE_TIMEOUT,
        }
    }
else:
    # Prod: Redis. DB 1 (broker Celery usa DB 0) para não colidir.
    # Override via CACHE_REDIS_URL se o broker tiver query-string (ex: rediss TLS).
    _broker_url = os.getenv("CELERY_BROKER_URL", "redis://127.0.0.1:6379/0")
    _cache_default_url = _broker_url.rsplit("/", 1)[0] + "/1"
    CACHES = {
        "default": {
            "BACKEND": "django.core.cache.backends.redis.RedisCache",
            "LOCATION": os.getenv("CACHE_REDIS_URL", _cache_default_url),
            "TIMEOUT": CACHE_TIMEOUT,
        }
    }

# Celery
CELERY_BROKER_URL = os.getenv("CELERY_BROKER_URL", "redis://127.0.0.1:6379/0")
CELERY_RESULT_BACKEND = os.getenv("CELERY_RESULT_BACKEND", "django-db")
CELERY_ACCEPT_CONTENT = ["json"]
CELERY_TASK_SERIALIZER = "json"
CELERY_RESULT_SERIALIZER = "json"
CELERY_TIMEZONE = os.getenv("CELERY_TIMEZONE", TIME_ZONE)
# Align scheduler/logs with local timezone when desired.
CELERY_ENABLE_UTC = os.getenv("CELERY_ENABLE_UTC", "0").lower() in ("1", "true", "yes")
# CELERY_EAGER=1: run tasks in-process (no Redis). Useful for dev without Docker.
CELERY_TASK_ALWAYS_EAGER = os.getenv("CELERY_EAGER", "").lower() in ("1", "true", "yes")
CELERY_TASK_DEFAULT_QUEUE = "processing"
# Queue names (override via env for custom deployments)
CELERY_QUEUE_TRANSCRIPTION = os.getenv("CELERY_QUEUE_TRANSCRIPTION", "transcription")
CELERY_QUEUE_RENDER = os.getenv("CELERY_QUEUE_RENDER", "render")
CELERY_TASK_ROUTES = {
    # Dedicated queue for publishing/scheduling (must not be blocked by transcription/render)
    "apps.social.tasks.check_scheduled_posts_task": {"queue": "publish"},
    "apps.social.tasks.process_brand_posting_queue_task": {"queue": "publish"},
    "apps.social.tasks.generate_daily_factory_schedules_task": {"queue": "publish"},
    "apps.social.tasks.post_to_platforms_task": {"queue": "publish"},
    "apps.social.tasks.reconcile_youtube_schedules_task": {"queue": "publish"},
    "apps.social.tasks.upload_thumbnails_after_batch_task": {"queue": "publish"},
    "apps.social.tasks.cleanup_posted_media_task": {"queue": "processing"},
    # Transcription (CPU) can run while another worker encodes on GPU (render queue)
    "apps.auto_cuts.tasks.analyze_auto_cuts_task": {"queue": CELERY_QUEUE_TRANSCRIPTION},
    "apps.jobs.tasks.generate_subtitles_task": {"queue": CELERY_QUEUE_TRANSCRIPTION},
    "apps.multiple_creator.tasks.multiple_creator_transcribe_task": {"queue": CELERY_QUEUE_TRANSCRIPTION},
    "apps.multiple_creator.tasks.multiple_creator_fanout_task": {"queue": CELERY_QUEUE_TRANSCRIPTION},
    "apps.multiple_creator.tasks.cleanup_terminal_job_files_task": {"queue": "processing"},
    # FFmpeg / NVENC final output (GPU when available)
    "apps.auto_cuts.tasks.finalizar_auto_cut_task": {"queue": CELERY_QUEUE_RENDER},
    "apps.jobs.tasks.process_job": {"queue": CELERY_QUEUE_RENDER},
    "apps.jobs.tasks.burn_subtitles_task": {"queue": CELERY_QUEUE_RENDER},
}
# Whisper: always CPU so GPU is free for NVENC (set WHISPER_FORCE_CPU=0 to allow .env / CUDA)
WHISPER_FORCE_CPU = os.getenv("WHISPER_FORCE_CPU", "1").lower() in ("1", "true", "yes")

# Whisper: modelo e device (refactor.md R-17 lote 2 / D-08 — fonte única de configuração)
# ⚠ WHISPER_MODEL tem DOIS defaults no código, e eles são diferentes entre si. Não é
# engano de digitação recente: a transcrição fatiada (vídeo longo, um bloco por vez) usa
# "small" e a de passada única usa "large-v3". Migrar para uma setting só apagaria essa
# diferença em produção, então as duas viram settings separadas, com o mesmo env var por
# trás. Quem quiser unificar: é decisão de qualidade × custo, não de refatoração.
_whisper_model_env = (os.getenv("WHISPER_MODEL", "") or "").strip()
WHISPER_MODEL_FULL = _whisper_model_env or "large-v3"
WHISPER_MODEL_CHUNKED = _whisper_model_env or "small"
# "cpu" força CPU mesmo com CUDA disponível; vazio deixa a decisão para WHISPER_FORCE_CPU.
WHISPER_DEVICE = os.getenv("WHISPER_DEVICE", "").strip().lower()
# Sem .lower() de propósito: era assim que os leitores comparavam, e "TRUE" não ligava.
WHISPER_DEBUG_GPU = os.getenv("WHISPER_DEBUG_GPU", "").strip() in ("1", "true", "yes")

# LLM (refactor.md R-17 lote 3 / D-08 — fonte única de configuração)
# As settings guardam o valor CRU já normalizado; a precedência entre elas continua em
# `services/grok.py:_build_llm_client`, que é onde ela sempre esteve e onde os avisos de
# depreciação são emitidos (uma vez por chamada, como antes).
LLM_PROVIDER = (os.getenv("LLM_PROVIDER") or "xai").strip().lower()
LLM_API_KEY = (os.getenv("LLM_API_KEY") or "").strip()
# Depreciada: usada só como fallback de LLM_API_KEY, com aviso no log.
XAI_API_KEY = (os.getenv("XAI_API_KEY") or "").strip()
LLM_MODEL = (os.getenv("LLM_MODEL") or "").strip()
LLM_MODEL_LIGHT = (os.getenv("LLM_MODEL_LIGHT") or "").strip()
# Depreciada: fallback de LLM_MODEL/LLM_MODEL_LIGHT, com aviso no log.
GROK_MODEL = (os.getenv("GROK_MODEL") or "").strip()
LLM_BASE_URL = (os.getenv("LLM_BASE_URL") or "").strip()
# Limites interpolados no prompt no momento da chamada. Valor inválido derruba o boot em
# vez de fazer cada análise falhar com ValueError no meio da task — é de propósito.
# Teto absoluto de candidatos pedidos ao LLM. Não é a quantidade: a quantidade sai do
# alvo do job multiplicado pela margem, e estes valores só limitam o resultado.
LLM_MAX_SHORTS = max(1, int(os.getenv("LLM_MAX_SHORTS", "10")))
LLM_MAX_LONGS = max(1, int(os.getenv("LLM_MAX_LONGS", "5")))
# Margem sobre o alvo do job. O backend descarta candidato por duração, por categoria
# sem brand mapeada e (a partir do filtro de nota) por score — pedir exatamente o alvo
# faz o job entregar menos do que pediu sempre que qualquer um desses filtra algo.
LLM_CANDIDATE_MARGIN = max(1.0, float(os.getenv("LLM_CANDIDATE_MARGIN", "1.5")))
# Override de tabela de preço do LLM, em JSON. Vazio = usa GROK_PRICING.
GROK_PRICING_JSON = (os.getenv("GROK_PRICING_JSON") or "").strip()
# Depuração: salva a resposta parseada do LLM em MEDIA_ROOT/grok_responses.
GROK_SAVE_RESPONSE_JSON = (os.getenv("GROK_SAVE_RESPONSE_JSON") or "").strip().lower() in (
    "1",
    "true",
    "yes",
)

# Upload-Post (refactor.md R-17 lote 4 / D-08 — fonte única de configuração)
# ⚠ Guardada CRUA, sem `.strip()`. O publisher (`publishers/upload_post.py`) usava o valor
# como veio e o cliente de analytics aplicava `.strip()` no seu próprio acessor. Normalizar
# aqui mudaria o que o publisher manda no header — se for para arrumar, é item próprio.
UPLOAD_POST_API_KEY = os.getenv("UPLOAD_POST_API_KEY") or ""
# Throttle do cliente de analytics: intervalo mínimo entre requisições, pausa global após
# 429/5xx (evita bloqueio de borda) e teto de espera dentro de uma única chamada.
UPLOAD_POST_ANALYTICS_MIN_INTERVAL_SEC = float(
    os.getenv("UPLOAD_POST_ANALYTICS_MIN_INTERVAL_SEC", "0.6")
)
UPLOAD_POST_ANALYTICS_COOLDOWN_SEC = float(os.getenv("UPLOAD_POST_ANALYTICS_COOLDOWN_SEC", "30"))
UPLOAD_POST_ANALYTICS_MAX_WAIT_SEC = float(os.getenv("UPLOAD_POST_ANALYTICS_MAX_WAIT_SEC", "5"))
# Pausa extra entre marcas no painel da factory, além do throttle do cliente HTTP.
UPLOAD_POST_FACTORY_BRAND_DELAY_SEC = float(
    os.getenv("UPLOAD_POST_FACTORY_BRAND_DELAY_SEC", "0.15")
)

# OAuth de Contas e YouTube Data API (refactor.md R-17 lote 6 / D-08)
# ⚠ Este redirect é o do OAuth de **Contas**. O do factory-check é o
# YOUTUBE_CHECK_REDIRECT_URI, mais abaixo — trocar um pelo outro quebra o fluxo em
# produção sem erro visível no código.
YOUTUBE_REDIRECT_URI = os.getenv(
    "YOUTUBE_REDIRECT_URI", "http://localhost:8000/api/youtube/callback/"
)
# Chave da YouTube Data API v3. GOOGLE_API_KEY é o nome antigo; a precedência entre as
# duas continua no leitor (`services/youtube_fetch.py`).
YOUTUBE_API_KEY = (os.getenv("YOUTUBE_API_KEY") or "").strip()
GOOGLE_API_KEY = (os.getenv("GOOGLE_API_KEY") or "").strip()
# Páginas de 50 vídeos por varredura completa do canal. Teto de 12 para não torrar a quota.
YOUTUBE_FULL_SCAN_MAX_PAGES = max(1, min(12, int(os.getenv("YOUTUBE_FULL_SCAN_MAX_PAGES", "4") or "4")))

# Criptografia de segredos em banco (refactor.md R-17 lote 6 / D-08)
# Vazia = `secret_crypto` levanta com mensagem própria; a API traduz para 400 legível.
SOCIAL_ENCRYPTION_KEY = (os.getenv("SOCIAL_ENCRYPTION_KEY") or "").strip()

# URL do frontend para redirect pós-OAuth (refactor.md R-17 lote 6 / D-08)
# ⚠ Esta é a leitura COM default de dev. As outras duas de `FRONTEND_URL` neste arquivo
# (ALLOWED_HOSTS e CORS) tratam ausência como "não acrescenta nada" — e é o certo: sem a
# variável, não há host extra a liberar, mas ainda tem que haver para onde redirecionar.
FRONTEND_URL = os.getenv("FRONTEND_URL", "http://localhost:5173")

# yt-dlp (refactor.md R-17 lote 5 / D-08 — fonte única de configuração)
# Todas vazias por omissão: cada uma liga um comportamento opcional do download.
YTDLP_YOUTUBE_PLAYER_CLIENTS = (os.getenv("YTDLP_YOUTUBE_PLAYER_CLIENTS") or "").strip()
YTDLP_JS_RUNTIMES = (os.getenv("YTDLP_JS_RUNTIMES") or "").strip()
YTDLP_COOKIES_FILE = (os.getenv("YTDLP_COOKIES_FILE") or "").strip()
YTDLP_COOKIES_FROM_BROWSER = (os.getenv("YTDLP_COOKIES_FROM_BROWSER") or "").strip()
# Altura mínima desejada do vídeo. `0` desliga o filtro. Valor inválido cai em 720 em vez
# de derrubar o boot — a tolerância é do código de origem e foi preservada aqui, porque
# esta é preferência de qualidade, não credencial: errar o número não impede o download.
_ytdlp_min_height_raw = (os.getenv("YTDLP_MIN_VIDEO_HEIGHT") or "").strip()
try:
    _ytdlp_min_height = int(_ytdlp_min_height_raw) if _ytdlp_min_height_raw else 720
except ValueError:
    _ytdlp_min_height = 720
YTDLP_MIN_VIDEO_HEIGHT = max(0, _ytdlp_min_height)

# Multiple-Creator: retencao do video original apos job terminal (DONE/PARTIAL/ERROR).
# Apos esse periodo, cleanup_terminal_job_files_task remove o file (mantem a row).
MULTIPLE_CREATOR_FILE_RETAIN_HOURS = int(os.getenv("MULTIPLE_CREATOR_FILE_RETAIN_HOURS", "24"))


# YouTube OAuth (refactor.md R-17 / D-08 — fonte única de configuração)
# Cliente "check": credencial separada, usada só para CONSULTAR o canal (reconciliação e
# busca de vídeos). Vazio = recurso desligado, e quem lê trata isso explicitamente.
# Já vem com .strip() para que o ponto de uso não precise repetir a normalização — era
# ela, copiada em 3 arquivos, que fazia a diferença entre "não configurado" e "espaço".
YOUTUBE_CHECK_CLIENT_ID = (os.getenv("YOUTUBE_CHECK_CLIENT_ID") or "").strip()
YOUTUBE_CHECK_CLIENT_SECRET = (os.getenv("YOUTUBE_CHECK_CLIENT_SECRET") or "").strip()
# Callback próprio do factory-check; NÃO reaproveitar YOUTUBE_REDIRECT_URI (é o de Contas).
YOUTUBE_CHECK_REDIRECT_URI = (
    (os.getenv("YOUTUBE_CHECK_REDIRECT_URI") or "").strip()
    or "http://127.0.0.1:8000/api/youtube/factory-check-callback/"
)
# Fallback global de OAuth quando a brand não tem cliente próprio. None quando ausente —
# o ponto de uso depende disso ser falsy, não string vazia.
GOOGLE_CLIENT_ID = os.getenv("GOOGLE_CLIENT_ID")
GOOGLE_CLIENT_SECRET = os.getenv("GOOGLE_CLIENT_SECRET")

# FFmpeg
FFMPEG_BIN = os.getenv("FFMPEG_BIN", "ffmpeg")
FFPROBE_BIN = os.getenv("FFPROBE_BIN", "ffprobe")
# libx264 (CPU): lower CRF = better quality (larger file); slower preset = better compression (more time).
FFMPEG_LIBX264_CRF = int(os.getenv("FFMPEG_LIBX264_CRF", "20"))
FFMPEG_LIBX264_PRESET = os.getenv("FFMPEG_LIBX264_PRESET", "veryfast")
# Subtitle burn (subtitles filter): omit = same CRF/preset as pipeline; avoids libx264 defaults.
FFMPEG_LIBX264_BURN_CRF = int(os.getenv("FFMPEG_LIBX264_BURN_CRF", str(FFMPEG_LIBX264_CRF)))
FFMPEG_LIBX264_BURN_PRESET = os.getenv("FFMPEG_LIBX264_BURN_PRESET", FFMPEG_LIBX264_PRESET)
# Side overlay on long video: step sensitive to artifacts — heavier default (slow + CRF 16).
FFMPEG_LIBX264_OVERLAY_LONG_CRF = int(os.getenv("FFMPEG_LIBX264_OVERLAY_LONG_CRF", "16"))
FFMPEG_LIBX264_OVERLAY_LONG_PRESET = os.getenv("FFMPEG_LIBX264_OVERLAY_LONG_PRESET", "slow")

# REST Framework
REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework_simplejwt.authentication.JWTAuthentication",
        "rest_framework.authentication.SessionAuthentication",
    ],
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticated",
    ],
}

# Simple JWT — access token valid for 1 day
SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(days=1),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=7),
}

# CORS — React dev server on localhost:5173
# For access from another machine on the LAN: set FRONTEND_URL=http://YOUR_IP:5173 in .env
_cors_origins = ["http://localhost:5173", "http://127.0.0.1:5173"]
_frontend_url = (os.getenv("FRONTEND_URL") or "").strip().rstrip("/")
if _frontend_url and _frontend_url not in _cors_origins:
    _cors_origins.append(_frontend_url)
CORS_ALLOWED_ORIGINS = _cors_origins

# Reduce Celery log noise: Google libs (file_cache, Refreshing credentials) at WARNING
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        # Plain formatter for most loggers (keeps existing behaviour).
        "default": {
            "format": "%(asctime)s %(levelname)s %(name)s %(message)s",
        },
        # JSON-line formatter for the schedule flow.
        # log_event() already serialises the payload to JSON, so the
        # message itself is a valid JSON string — this formatter just passes it
        # through unchanged so log aggregators (Loki, CloudWatch, etc.) can
        # parse it directly.
        "json": {
            "format": "%(message)s",
        },
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "default",
        },
        "console_json": {
            "class": "logging.StreamHandler",
            "formatter": "json",
        },
    },
    "loggers": {
        "google": {"level": "WARNING"},
        "google.auth": {"level": "WARNING"},
        "googleapiclient": {"level": "WARNING"},
        # Schedule-flow loggers emit structured JSON via log_event().
        "apps.jobs.services.factory_scheduler": {
            "handlers": ["console_json"],
            "level": "INFO",
            "propagate": False,
        },
        "apps.jobs.services.daily_posting_plan_service": {
            "handlers": ["console_json"],
            "level": "INFO",
            "propagate": False,
        },
        "apps.social.tasks": {
            "handlers": ["console_json"],
            "level": "INFO",
            "propagate": False,
        },
        # Transcription and render loggers also emit structured JSON.
        "apps.jobs.tasks": {
            "handlers": ["console_json"],
            "level": "INFO",
            "propagate": False,
        },
        "apps.auto_cuts.tasks": {
            "handlers": ["console_json"],
            "level": "INFO",
            "propagate": False,
        },
    },
}
