# Generated by Django 5.2.11 on 2026-02-18 13:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('brands', '0001_initial'),
        ('cuts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('IG', 'Instagram Reels'), ('TT', 'TikTok'), ('YT', 'YouTube Shorts')], default='YT', max_length=8)),
                ('make_vertical', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('QUEUED', 'Queued'), ('RUNNING', 'Running'), ('DONE', 'Done'), ('FAILED', 'Failed')], default='QUEUED', max_length=10)),
                ('progress', models.PositiveSmallIntegerField(default=0)),
                ('log', models.TextField(blank=True, default='')),
                ('error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('cut', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='cuts.cut')),
                ('intro_asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='brands.brandasset')),
                ('outro_asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='brands.brandasset')),
            ],
        ),
        migrations.CreateModel(
            name='RenderOutput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='exports/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='output', to='jobs.job')),
            ],
        ),
    ]
