# Generated by Django 5.2.11 on 2026-02-18 20:38

import apps.jobs.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_target_platforms'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jobcut',
            options={'ordering': ['id'], 'verbose_name': 'Corte do job', 'verbose_name_plural': 'Cortes do job'},
        ),
        migrations.AlterField(
            model_name='job',
            name='target_platforms',
            field=models.JSONField(default=apps.jobs.models.Job._default_platforms, help_text='Redes onde o vídeo será postado automaticamente. Marque as que deseja usar.'),
        ),
        migrations.AlterField(
            model_name='jobcut',
            name='order',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
