# Generated by Django 5.2.11 on 2026-02-18 20:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_alter_jobcut_options_alter_job_target_platforms_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ScheduledPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platforms', models.JSONField(default=list, help_text='Lista de códigos: IG, TT, YT, YTB')),
                ('scheduled_at', models.DateTimeField(help_text='Data/hora para publicar')),
                ('status', models.CharField(choices=[('PENDING', 'Pendente'), ('POSTING', 'Postando'), ('DONE', 'Concluído'), ('FAILED', 'Falhou')], default='PENDING', max_length=10)),
                ('error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_posts', to='jobs.job')),
            ],
        ),
    ]
