# Generated by Django 5.2.11 on 2026-02-18 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0007_job_user_scheduledpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='name',
            field=models.CharField(blank=True, default='', help_text='Nome para identificar o job no dashboard', max_length=200),
        ),
    ]
