# Generated by Django 5.2.11 on 2026-02-19 16:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0001_initial'),
        ('jobs', '0009_add_archived'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='brand',
            field=models.ForeignKey(blank=True, help_text='Marca para filtrar e isolar jobs', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='brands.brand'),
        ),
    ]
