# Generated by Django 5.2.11 on 2026-02-19 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0010_add_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='subtitle_error',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='job',
            name='subtitle_segments',
            field=models.JSONField(blank=True, help_text='[{start, end, text}, ...]', null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='subtitle_status',
            field=models.CharField(blank=True, help_text='generating, ready_for_edit, burning, burned, error', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='subtitle_style',
            field=models.JSONField(blank=True, help_text='{font, size, color, outline_color, position}', null=True),
        ),
    ]
