# Generated by Django 5.2.11 on 2026-03-04 19:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0002_add_brand_social_account_and_scheduled_post_fk'),
        ('jobs', '0011_add_subtitle_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduledpost',
            name='social_account',
            field=models.ForeignKey(blank=True, help_text='Conta a usar (opcional; se vazio, usa primeira conta da marca para a plataforma)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scheduled_posts', to='brands.brandsocialaccount'),
        ),
    ]
