# Generated by Django 5.2.11 on 2026-03-04 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0012_add_brand_social_account_and_scheduled_post_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduledpost',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='scheduledpost',
            name='privacy_status',
            field=models.CharField(choices=[('public', 'Público'), ('private', 'Privado'), ('unlisted', 'Não listado')], default='private', max_length=12),
        ),
        migrations.AddField(
            model_name='scheduledpost',
            name='tags',
            field=models.JSONField(default=list, help_text='Lista de tags/keywords'),
        ),
        migrations.AddField(
            model_name='scheduledpost',
            name='title',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
