# Generated by Django 5.2.11 on 2026-03-04 19:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto_cuts', '0007_add_english_prompt_versions'),
        ('jobs', '0013_add_scheduled_post_metadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduledpost',
            name='auto_cut_corte',
            field=models.ForeignKey(blank=True, help_text='Corte finalizado do Auto Cuts (opcional).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_posts', to='auto_cuts.autocutcorte'),
        ),
        migrations.AlterField(
            model_name='scheduledpost',
            name='job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_posts', to='jobs.job'),
        ),
    ]
