# Generated by Django 5.2.11 on 2026-03-04 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0014_scheduledpost_auto_cut_corte_alter_scheduledpost_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduledpost',
            name='external_ids',
            field=models.JSONField(default=dict, help_text="IDs externos por plataforma (ex.: {'YT': 'abc123'})."),
        ),
        migrations.AddField(
            model_name='scheduledpost',
            name='retry_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='scheduledpost',
            name='upload_fingerprint',
            field=models.CharField(blank=True, default='', help_text='SHA-256 do arquivo enviado para deduplicação por canal/plataforma.', max_length=64),
        ),
    ]
