# Generated by Django 5.2.11 on 2026-03-06 19:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto_cuts', '0013_autocutsuggestion_source_asset_id_and_more'),
        ('brands', '0005_factory_brand_long_window_end_and_more'),
        ('jobs', '0015_scheduledpost_external_ids_scheduledpost_retry_count_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FactoryPostingSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_type', models.CharField(choices=[('SHORT', 'Short'), ('LONG', 'Long')], max_length=8)),
                ('scheduled_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('PLANNED', 'Planejado'), ('POSTING', 'Postando'), ('DONE', 'Concluído'), ('FAILED', 'Falhou'), ('SKIPPED', 'Ignorado')], default='PLANNED', max_length=12)),
                ('attempt_count', models.PositiveSmallIntegerField(default=0)),
                ('next_retry_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posting_schedules', to='brands.brand')),
                ('factory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posting_schedules', to='brands.factory')),
                ('scheduled_post', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='factory_schedule', to='jobs.scheduledpost')),
            ],
            options={
                'ordering': ['scheduled_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='FactoryPostingAttemptLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempt_number', models.PositiveSmallIntegerField(default=1)),
                ('started_at', models.DateTimeField()),
                ('finished_at', models.DateTimeField()),
                ('result', models.CharField(choices=[('SUCCESS', 'Sucesso'), ('ERROR', 'Erro')], max_length=10)),
                ('error_code', models.CharField(blank=True, default='', max_length=120)),
                ('error_message', models.TextField(blank=True, default='')),
                ('provider_response', models.JSONField(blank=True, default=dict)),
                ('posting_schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempt_logs', to='jobs.factorypostingschedule')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='VideoInventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_type', models.CharField(choices=[('SHORT', 'Short'), ('LONG', 'Long')], max_length=8)),
                ('title', models.CharField(blank=True, default='', max_length=220)),
                ('description', models.TextField(blank=True, default='')),
                ('virality_score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('source_asset_id', models.CharField(blank=True, default='', max_length=120)),
                ('source_metadata', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('AVAILABLE', 'Disponível'), ('SCHEDULED', 'Agendado'), ('POSTING', 'Postando'), ('POSTED', 'Postado'), ('FAILED', 'Falhou')], default='AVAILABLE', max_length=12)),
                ('scheduled_for', models.DateTimeField(blank=True, null=True)),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('attempt_count', models.PositiveSmallIntegerField(default=0)),
                ('last_error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('auto_cut_corte', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inventory_item', to='auto_cuts.autocutcorte')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_inventory_items', to='brands.brand')),
                ('factory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_inventory_items', to='brands.factory')),
            ],
            options={
                'ordering': ['status', '-virality_score', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PostedVideoLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_platform', models.CharField(default='YT', max_length=8)),
                ('external_video_id', models.CharField(blank=True, default='', max_length=120)),
                ('posted_at', models.DateTimeField()),
                ('metadata_snapshot', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posted_video_logs', to='brands.brand')),
                ('factory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posted_video_logs', to='brands.factory')),
                ('inventory_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posted_logs', to='jobs.videoinventoryitem')),
            ],
            options={
                'ordering': ['-posted_at', '-id'],
            },
        ),
        migrations.AddField(
            model_name='factorypostingschedule',
            name='inventory_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posting_schedules', to='jobs.videoinventoryitem'),
        ),
        migrations.CreateModel(
            name='FactoryScheduleRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_date', models.DateField(help_text='Data local da factory em que a geração ocorreu.')),
                ('timezone', models.CharField(default='America/Sao_Paulo', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('factory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_runs', to='brands.factory')),
            ],
            options={
                'ordering': ['-run_date', '-id'],
                'unique_together': {('factory', 'run_date')},
            },
        ),
    ]
