# Generated by Django 5.2.12 on 2026-03-30 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0017_preserve_schedule_history_on_delete'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='correlation_id',
            field=models.CharField(blank=True, db_index=True, default='', help_text='ID estável para tracing deste job entre tasks Celery (transcrição, render, pipeline).', max_length=64),
        ),
        migrations.AddField(
            model_name='scheduledpost',
            name='correlation_id',
            field=models.CharField(blank=True, db_index=True, default='', help_text='ID estável para tracing da publicação (AutoCut sem Job). Com Job, usa Job.correlation_id.', max_length=64),
        ),
    ]
