# Generated by Django 5.2.12 on 2026-03-30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0018_job_and_scheduled_post_correlation_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="scheduledpost",
            name="youtube_quota_retry_count",
            field=models.PositiveSmallIntegerField(
                default=0,
                help_text="Tentativas por quotaExceeded (YouTube); após o máximo o post falha e o vídeo volta ao inventário.",
            ),
        ),
    ]
