# Generated by Django 5.2.12 on 2026-04-02 18:25

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0033_brand_active_weekdays_brand_base_end_time_and_more'),
        ('jobs', '0019_scheduledpost_youtube_quota_retry_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyPostingPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_date', models.DateField(db_index=True)),
                ('timezone', models.CharField(default='America/Sao_Paulo', max_length=64)),
                ('generated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('DRAFT', 'Rascunho'), ('GENERATED', 'Gerado'), ('SKIPPED', 'Ignorado'), ('ERROR', 'Erro')], default='DRAFT', max_length=16)),
                ('planned_posts_count', models.PositiveSmallIntegerField(default=0)),
                ('config_snapshot', models.JSONField(blank=True, default=dict)),
                ('last_error', models.TextField(blank=True, default='')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_posting_plans', to='brands.brand')),
            ],
            options={
                'ordering': ['-plan_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='DailyPostingPlanItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_index', models.PositiveSmallIntegerField(default=0, help_text='Ordem do item no dia (0..N-1).')),
                ('video_type', models.CharField(choices=[('SHORT', 'Short'), ('LONG', 'Longo')], max_length=8)),
                ('scheduled_at', models.DateTimeField(help_text='Instante UTC planejado para publicação.')),
                ('status', models.CharField(choices=[('PLANNED', 'Planejado'), ('CONSUMED', 'Consumido'), ('SKIPPED', 'Ignorado'), ('FAILED', 'Falhou')], default='PLANNED', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('inventory_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daily_plan_items', to='jobs.videoinventoryitem')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='jobs.dailypostingplan')),
                ('scheduled_post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daily_plan_items', to='jobs.scheduledpost')),
            ],
            options={
                'ordering': ['plan', 'order_index', 'id'],
            },
        ),
        migrations.AddField(
            model_name='factorypostingschedule',
            name='daily_plan_item',
            field=models.ForeignKey(blank=True, help_text='Item do plano diário que originou este agendamento (auditoria).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='factory_posting_schedules', to='jobs.dailypostingplanitem'),
        ),
        migrations.AddConstraint(
            model_name='dailypostingplan',
            constraint=models.UniqueConstraint(fields=('brand', 'plan_date'), name='uniq_daily_plan_brand_date'),
        ),
        migrations.AddConstraint(
            model_name='dailypostingplanitem',
            constraint=models.UniqueConstraint(fields=('plan', 'order_index'), name='uniq_daily_plan_item_order'),
        ),
    ]
