# Generated by Django 5.2.12 on 2026-04-03 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0020_dailypostingplan_dailypostingplanitem_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="IdempotencyKey",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("key", models.CharField(max_length=255, unique=True)),
                ("operation_name", models.CharField(max_length=64)),
                ("aggregate_type", models.CharField(max_length=64)),
                ("aggregate_id", models.PositiveBigIntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("in_progress", "Em andamento"),
                            ("succeeded", "Concluída"),
                            ("failed", "Falhou"),
                        ],
                        default="in_progress",
                        max_length=20,
                    ),
                ),
                ("result_payload", models.JSONField(blank=True, default=dict)),
                ("error_message", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Chave de idempotência",
                "verbose_name_plural": "Chaves de idempotência",
            },
        ),
        migrations.AddIndex(
            model_name="idempotencykey",
            index=models.Index(
                fields=["operation_name", "aggregate_type", "aggregate_id"],
                name="jobs_idemp_agg_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="idempotencykey",
            index=models.Index(fields=["status", "updated_at"], name="jobs_idemp_status_idx"),
        ),
    ]
