# Generated by Django 5.2.12 on 2026-04-03 22:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0021_idempotencykey'),
    ]

    operations = [
        migrations.CreateModel(
            name='PipelineExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pipeline_type', models.CharField(max_length=64)),
                ('aggregate_type', models.CharField(max_length=64)),
                ('aggregate_id', models.PositiveBigIntegerField()),
                ('correlation_id', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=16)),
                ('current_stage', models.CharField(blank=True, default='', max_length=64)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('failure_reason', models.TextField(blank=True, default='')),
                ('metadata_json', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at', '-id'],
                'indexes': [models.Index(fields=['aggregate_type', 'aggregate_id'], name='jobs_pipe_exec_agg_idx'), models.Index(fields=['status', 'pipeline_type'], name='jobs_pipe_exec_status_idx')],
                'constraints': [models.UniqueConstraint(fields=('pipeline_type', 'aggregate_type', 'aggregate_id'), name='jobs_pipe_exec_scope_uniq')],
            },
        ),
        migrations.CreateModel(
            name='StageExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage_name', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('queued', 'Queued'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('skipped', 'Skipped')], default='pending', max_length=16)),
                ('queue_name', models.CharField(blank=True, default='', max_length=64)),
                ('task_name', models.CharField(blank=True, default='', max_length=255)),
                ('retry_count', models.PositiveSmallIntegerField(default=0)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('duration_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('input_payload', models.JSONField(blank=True, default=dict)),
                ('output_payload', models.JSONField(blank=True, default=dict)),
                ('error_class', models.CharField(blank=True, default='', max_length=255)),
                ('error_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pipeline_execution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stage_executions', to='jobs.pipelineexecution')),
            ],
            options={
                'ordering': ['pipeline_execution_id', 'id'],
                'indexes': [models.Index(fields=['pipeline_execution', 'status'], name='jobs_stage_exec_status_idx'), models.Index(fields=['stage_name', 'status'], name='jobs_stage_exec_name_idx')],
                'constraints': [models.UniqueConstraint(fields=('pipeline_execution', 'stage_name'), name='jobs_stage_exec_name_uniq')],
            },
        ),
    ]
