# Generated by Django 5.2.12 on 2026-04-03 22:53

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0022_pipelineexecution_stageexecution'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeadLetterJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aggregate_type', models.CharField(max_length=64)),
                ('aggregate_id', models.PositiveBigIntegerField()),
                ('job_name', models.CharField(max_length=255)),
                ('queue_name', models.CharField(blank=True, default='', max_length=64)),
                ('correlation_id', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('payload_json', models.JSONField(blank=True, default=dict)),
                ('error_class', models.CharField(blank=True, default='', max_length=255)),
                ('error_message', models.TextField(blank=True, default='')),
                ('error_category', models.CharField(choices=[('retryable', 'Retryable'), ('non_retryable', 'Non retryable'), ('infra', 'Infra'), ('poison', 'Poison'), ('unknown', 'Unknown')], default='unknown', max_length=32)),
                ('status', models.CharField(choices=[('open', 'Open'), ('replayed', 'Replayed'), ('ignored', 'Ignored')], default='open', max_length=16)),
                ('retry_count', models.PositiveSmallIntegerField(default=0)),
                ('first_failed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_failed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('replayed_at', models.DateTimeField(blank=True, null=True)),
                ('replay_result_json', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pipeline_execution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dead_letter_jobs', to='jobs.pipelineexecution')),
                ('replayed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replayed_dead_letter_jobs', to=settings.AUTH_USER_MODEL)),
                ('stage_execution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dead_letter_jobs', to='jobs.stageexecution')),
            ],
            options={
                'ordering': ['-updated_at', '-id'],
                'indexes': [models.Index(fields=['aggregate_type', 'aggregate_id'], name='jobs_dlj_agg_idx'), models.Index(fields=['status', 'error_category'], name='jobs_dlj_status_cat_idx'), models.Index(fields=['job_name', 'status'], name='jobs_dlj_job_status_idx')],
            },
        ),
    ]
