# Generated by Django 5.2.11 on 2026-02-18 13:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('slug', models.SlugField(max_length=120, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='BrandAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_type', models.CharField(choices=[('LOGO', 'Logo'), ('FRAME', 'Frame/Moldura'), ('INTRO', 'Intro vídeo'), ('OUTRO', 'Outro vídeo'), ('CTA', 'CTA vídeo/imagem')], max_length=16)),
                ('file', models.FileField(upload_to='brands/assets/')),
                ('label', models.CharField(blank=True, default='', max_length=120)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='brands.brand')),
            ],
            options={
                'unique_together': {('brand', 'asset_type', 'label')},
            },
        ),
    ]
