# Generated by Django 5.2.11 on 2026-03-04 19:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brandasset',
            name='asset_type',
            field=models.CharField(choices=[('LOGO', 'Logo'), ('FRAME', 'Frame/Moldura'), ('INTRO', 'Intro vídeo'), ('OUTRO', 'Outro vídeo'), ('CTA', 'CTA vídeo/imagem'), ('ANIMATION', 'Animação overlay (PNG/GIF com transparência)')], max_length=16),
        ),
        migrations.CreateModel(
            name='BrandSocialAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('IG', 'Instagram'), ('TT', 'TikTok'), ('YT', 'YouTube Shorts'), ('YTB', 'YouTube')], max_length=4)),
                ('channel_id', models.CharField(blank=True, default='', max_length=64)),
                ('account_name', models.CharField(blank=True, default='', max_length=120)),
                ('access_token', models.TextField(blank=True, default='')),
                ('refresh_token', models.TextField(blank=True, default='')),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_accounts', to='brands.brand')),
            ],
            options={
                'verbose_name': 'Conta social',
                'verbose_name_plural': 'Contas sociais',
                'unique_together': {('brand', 'platform', 'channel_id')},
            },
        ),
    ]
