# Generated by Django 5.2.11 on 2026-03-04 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0002_add_brand_social_account_and_scheduled_post_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='youtube_description_extra',
            field=models.TextField(blank=True, default='', help_text='Texto adicional padrão da descrição para uploads no YouTube.'),
        ),
    ]
