# Generated by Django 5.2.11 on 2026-03-04 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0003_brand_youtube_description_extra'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='youtube_made_for_kids',
            field=models.BooleanField(default=False, help_text='Se verdadeiro, vídeos da marca são marcados como conteúdo infantil no YouTube.'),
        ),
    ]
