# Generated by Django 5.2.11 on 2026-03-06 19:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0004_brand_youtube_made_for_kids'),
    ]

    operations = [
        migrations.CreateModel(
            name='Factory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('timezone', models.CharField(default='America/Sao_Paulo', help_text='Timezone padrão da factory (IANA). Ex: America/Sao_Paulo.', max_length=64)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Factory',
                'verbose_name_plural': 'Factories',
            },
        ),
        migrations.AddField(
            model_name='brand',
            name='long_window_end',
            field=models.TimeField(blank=True, help_text='Fim da janela de postagem de longos.', null=True),
        ),
        migrations.AddField(
            model_name='brand',
            name='long_window_start',
            field=models.TimeField(blank=True, help_text='Início da janela de postagem de longos.', null=True),
        ),
        migrations.AddField(
            model_name='brand',
            name='max_longs_per_day',
            field=models.PositiveIntegerField(default=1, help_text='Máximo de vídeos longos por dia.'),
        ),
        migrations.AddField(
            model_name='brand',
            name='max_shorts_per_day',
            field=models.PositiveIntegerField(default=3, help_text='Máximo de shorts por dia.'),
        ),
        migrations.AddField(
            model_name='brand',
            name='min_long_interval_minutes',
            field=models.PositiveIntegerField(default=180, help_text='Intervalo mínimo entre vídeos longos (min).'),
        ),
        migrations.AddField(
            model_name='brand',
            name='min_short_interval_minutes',
            field=models.PositiveIntegerField(default=60, help_text='Intervalo mínimo entre shorts (min).'),
        ),
        migrations.AddField(
            model_name='brand',
            name='short_window_end',
            field=models.TimeField(blank=True, help_text='Fim da janela de postagem de shorts.', null=True),
        ),
        migrations.AddField(
            model_name='brand',
            name='short_window_start',
            field=models.TimeField(blank=True, help_text='Início da janela de postagem de shorts.', null=True),
        ),
        migrations.AddField(
            model_name='brand',
            name='theme_category',
            field=models.CharField(blank=True, choices=[('BUSINESS_MONEY', 'Negócios / Dinheiro'), ('PSYCHOLOGY_RELATIONSHIPS', 'Psicologia / Relacionamentos'), ('STORIES_CURIOSITIES', 'Histórias e Curiosidades'), ('CONTROVERSIES_DEBATE', 'Polêmicas / Debate'), ('COMEDY_HUMOR', 'Comédia / Humor')], default='', help_text='Categoria principal da brand dentro da factory (1:1 por factory).', max_length=40),
        ),
        migrations.AddField(
            model_name='brand',
            name='thumbnail_band_color',
            field=models.CharField(default='#E12E20', help_text='Cor da faixa da thumbnail (#RRGGBB).', max_length=7),
        ),
        migrations.AddField(
            model_name='brand',
            name='thumbnail_effect_color',
            field=models.CharField(default='#FFEBDC', help_text='Cor do contorno/efeito do texto da thumbnail (#RRGGBB).', max_length=7),
        ),
        migrations.AddField(
            model_name='brand',
            name='thumbnail_font',
            field=models.CharField(choices=[('anton', 'Anton'), ('bebas', 'Bebas Neue'), ('montserrat', 'Montserrat ExtraBold'), ('impact', 'Impact')], default='impact', help_text='Fonte padrão para thumbnails da brand.', max_length=20),
        ),
        migrations.AddField(
            model_name='brand',
            name='thumbnail_text_color',
            field=models.CharField(default='#0A0A0A', help_text='Cor principal do texto da thumbnail (#RRGGBB).', max_length=7),
        ),
        migrations.AddField(
            model_name='brand',
            name='factory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='brands', to='brands.factory'),
        ),
        migrations.AddConstraint(
            model_name='brand',
            constraint=models.UniqueConstraint(condition=models.Q(('theme_category', ''), _negated=True), fields=('factory', 'theme_category'), name='uniq_theme_category_per_factory'),
        ),
    ]
