# Generated by Django 5.2.11 on 2026-03-06 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0005_factory_brand_long_window_end_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='factory',
            name='scheduling_paused',
            field=models.BooleanField(default=False, help_text='Quando ativo, pausa apenas o agendamento/publicação da factory.'),
        ),
    ]
