# Generated by Django 5.2.12 on 2026-03-10 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0010_factory_daily_schedule_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='brandyoutubecredential',
            name='is_for_check',
            field=models.BooleanField(default=False, help_text='Se True, usada apenas para reconciliação/check do YouTube (YOUTUBE_CHECK_*).'),
        ),
    ]
