# Generated by Django 5.2.12 on 2026-03-10 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0011_brandyoutubecredential_is_for_check'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factory',
            name='daily_schedule_start_time',
            field=models.TimeField(blank=True, default=None, help_text='Horário fixo (ex: 19:00) em que o sistema agenda os vídeos para o dia seguinte. Padrão 19h.', null=True),
        ),
    ]
