# Generated by Django 5.2.12 on 2026-03-13 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0018_processed_youtube_video_and_max_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='short_slot_times',
            field=models.JSONField(blank=True, default=list, help_text="Horários fixos de shorts por dia (ex: ['10:00', '14:00', '18:00']). Obrigatório."),
        ),
    ]
