# Generated by Django 5.2.12 on 2026-03-13 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0019_alter_brand_short_slot_times'),
    ]

    operations = [
        migrations.AddField(
            model_name='factory',
            name='auto_fetch_longs_target',
            field=models.PositiveSmallIntegerField(default=3, help_text='Quantidade de cortes longos por job criado pela busca automática.'),
        ),
        migrations.AddField(
            model_name='factory',
            name='auto_fetch_prompt_version',
            field=models.CharField(choices=[('viral', 'Viral (PT)'), ('educational', 'Educacional (PT)'), ('viral_en', 'Viral (EN)'), ('educational_en', 'Educacional (EN)'), ('viral_translate', 'Viral Translate - EN to PT')], default='viral', help_text='Modo de análise usado nos jobs criados pela busca automática (válido para todas as brands da factory).', max_length=24),
        ),
        migrations.AddField(
            model_name='factory',
            name='auto_fetch_shorts_target',
            field=models.PositiveSmallIntegerField(default=12, help_text='Quantidade de cortes curtos (Shorts) por job criado pela busca automática.'),
        ),
    ]
