# Generated by Django 5.2.12 on 2026-03-13 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0020_auto_fetch_job_params'),
    ]

    operations = [
        migrations.AddField(
            model_name='factory',
            name='auto_fetch_min_duration_minutes',
            field=models.PositiveSmallIntegerField(
                default=50,
                help_text='Duração mínima do vídeo em minutos. Ignora cortes/shorts que os canais postam (ex: 50 min).',
            ),
        ),
    ]
