# Generated by Django 5.2.12 on 2026-03-13 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0021_factory_auto_fetch_min_duration_minutes'),
    ]

    operations = [
        migrations.AddField(
            model_name='factory',
            name='auto_fetch_min_views',
            field=models.PositiveIntegerField(
                default=0,
                help_text='Mínimo de visualizações. 0 = sem filtro. Ex: 10000 para só vídeos com 10k+ views.',
            ),
        ),
    ]
