# Generated by Django 5.2.12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0022_factory_auto_fetch_min_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='vertical_mode',
            field=models.CharField(
                choices=[('zoom_crop', 'Zoom e corte'), ('frame_center', 'Enquadrar e centralizar')],
                default='zoom_crop',
                help_text='Modo de reenquadramento vertical para shorts (16:9 → 9:16). Zoom preenche a tela; Enquadrar adiciona bordas e logo.',
                max_length=20,
            ),
        ),
    ]
