# Generated by Django 5.2.12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0023_brand_vertical_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchchannel',
            name='distribute_by_brands',
            field=models.BooleanField(
                default=False,
                help_text='Se ativo, ignora tema e distribui para a brand com menos vídeos no banco (equilibra estoque).',
            ),
        ),
    ]
