# Generated by Django 5.2.12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0024_searchchannel_distribute_by_brands'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='upload_post_tiktok_enabled',
            field=models.BooleanField(
                default=False,
                help_text='Se ativo, envia vídeos também para TikTok via Upload-Post (perfil = brand_{id}).',
            ),
        ),
        migrations.AddField(
            model_name='brand',
            name='upload_post_tiktok_extra_description',
            field=models.TextField(
                blank=True,
                default='',
                help_text='Texto extra na descrição do TikTok. Se vazio, usa só o que a LLM retornar.',
            ),
        ),
        migrations.AddField(
            model_name='brand',
            name='upload_post_x_enabled',
            field=models.BooleanField(
                default=False,
                help_text='Se ativo, envia vídeos também para X (Twitter) via Upload-Post.',
            ),
        ),
        migrations.AddField(
            model_name='brand',
            name='upload_post_x_extra_description',
            field=models.TextField(
                blank=True,
                default='',
                help_text='Texto extra na descrição do X. Se vazio, usa só o que a LLM retornar.',
            ),
        ),
        migrations.AddField(
            model_name='brand',
            name='upload_post_instagram_enabled',
            field=models.BooleanField(
                default=False,
                help_text='Se ativo, envia vídeos também para Instagram via Upload-Post.',
            ),
        ),
        migrations.AddField(
            model_name='brand',
            name='upload_post_instagram_extra_description',
            field=models.TextField(
                blank=True,
                default='',
                help_text='Texto extra na descrição do Instagram. Se vazio, usa só o que a LLM retornar.',
            ),
        ),
    ]
