# Generated by Django 5.2.12 on 2026-03-16 22:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0025_add_upload_post_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='factory',
            name='send_thumbnail',
            field=models.BooleanField(default=False, help_text='Quando ativo, envia capas customizadas para Shorts no YouTube. Desative se houver excesso de envio (quota).'),
        ),
        migrations.AlterField(
            model_name='brandasset',
            name='asset_type',
            field=models.CharField(choices=[('LOGO', 'Logo'), ('FRAME', 'Frame/Moldura'), ('INTRO', 'Intro vídeo'), ('OUTRO', 'Outro vídeo'), ('CTA', 'CTA vídeo/imagem'), ('ANIMATION', 'Animação overlay (PNG/GIF com transparência)'), ('THUMB_SHORT', 'Thumb Shorts'), ('THUMB_LONG', 'Thumb Longs')], max_length=16),
        ),
        migrations.AlterField(
            model_name='searchchannel',
            name='target_brand',
            field=models.ForeignKey(blank=True, help_text='Se preenchido, vídeos vão para este canal. Se vazio e distribute_by_brands=False, usa theme_category da IA.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='search_channels_targeted', to='brands.brand'),
        ),
    ]
