# Generated by Django 5.2.12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0026_add_send_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='factory',
            name='auto_fetch_last_empty_at',
            field=models.DateTimeField(
                blank=True,
                null=True,
                help_text='Quando a busca automática não encontrou nenhum vídeo novo. Evita tentativas repetidas até o dia seguinte (protege cota da API YouTube).',
            ),
        ),
    ]
