# Generated by Django 5.2.12 on 2026-03-24 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0031_brand_long_video_subtitles_and_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factory',
            name='send_thumbnail',
            field=models.BooleanField(default=False, help_text='Legado: o envio automático de capa de Shorts ao YouTube está desligado no código; capas continuam sendo geradas localmente.'),
        ),
    ]
