# Generated by Django 5.2.12 on 2026-04-02 18:25

from datetime import time

from django.db import migrations, models


def _parse_hhmm(s: str):
    s = (s or "").strip()
    if not s:
        return None
    parts = s.split(":")
    if len(parts) < 2:
        return None
    try:
        h, m = int(parts[0]), int(parts[1])
        if 0 <= h <= 23 and 0 <= m <= 59:
            return time(h, m)
    except (ValueError, TypeError):
        pass
    return None


def backfill_scheduler_from_legacy_slots(apps, schema_editor):
    """Preenche janela e volumes a partir de short_slot_times/long_slot_times legados."""
    Brand = apps.get_model("brands", "Brand")
    for b in Brand.objects.all():
        shorts = b.short_slot_times or []
        longs = b.long_slot_times or []
        parsed = []
        for raw in list(shorts) + list(longs):
            t = _parse_hhmm(str(raw))
            if t:
                parsed.append(t)
        if parsed:
            b.base_start_time = min(parsed)
            b.base_end_time = max(parsed)
            n_short = len([x for x in shorts if _parse_hhmm(str(x))])
            n_long = len([x for x in longs if _parse_hhmm(str(x))])
            total = max(1, n_short + n_long)
            b.daily_min_posts = min(total, 3)
            b.daily_max_posts = max(b.daily_min_posts, total)
            b.daily_min_long_posts = 0
            b.daily_max_long_posts = max(0, min(1, n_long)) if n_long else 1
            b.save(
                update_fields=[
                    "base_start_time",
                    "base_end_time",
                    "daily_min_posts",
                    "daily_max_posts",
                    "daily_min_long_posts",
                    "daily_max_long_posts",
                ]
            )


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0032_alter_factory_send_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='active_weekdays',
            field=models.JSONField(blank=True, default=list, help_text='Dias ativos: 0=segunda … 6=domingo (weekday() Python). Lista vazia = todos os dias.'),
        ),
        migrations.AddField(
            model_name='brand',
            name='base_end_time',
            field=models.TimeField(blank=True, help_text='Fim base da janela operacional.', null=True),
        ),
        migrations.AddField(
            model_name='brand',
            name='base_start_time',
            field=models.TimeField(blank=True, help_text='Início base da janela operacional (hora local conforme timezone do scheduler).', null=True),
        ),
        migrations.AddField(
            model_name='brand',
            name='daily_max_long_posts',
            field=models.PositiveSmallIntegerField(default=1, help_text='Máximo de vídeos longos por dia (dentro do total).'),
        ),
        migrations.AddField(
            model_name='brand',
            name='daily_max_posts',
            field=models.PositiveSmallIntegerField(default=4, help_text='Máximo de publicações no dia.'),
        ),
        migrations.AddField(
            model_name='brand',
            name='daily_min_long_posts',
            field=models.PositiveSmallIntegerField(default=0, help_text='Mínimo de vídeos longos por dia (dentro do total).'),
        ),
        migrations.AddField(
            model_name='brand',
            name='daily_min_posts',
            field=models.PositiveSmallIntegerField(default=3, help_text='Mínimo de publicações no dia (shorts + longos).'),
        ),
        migrations.AddField(
            model_name='brand',
            name='end_jitter_minutes',
            field=models.PositiveSmallIntegerField(default=0, help_text='Jitter máximo aplicado ao fim da janela (minutos).'),
        ),
        migrations.AddField(
            model_name='brand',
            name='max_gap_minutes',
            field=models.PositiveSmallIntegerField(default=360, help_text='Intervalo máximo entre posts consecutivos (minutos).'),
        ),
        migrations.AddField(
            model_name='brand',
            name='min_gap_minutes',
            field=models.PositiveSmallIntegerField(default=60, help_text='Intervalo mínimo entre posts consecutivos (minutos).'),
        ),
        migrations.AddField(
            model_name='brand',
            name='scheduler_enabled',
            field=models.BooleanField(default=True, help_text='Se falso, o plano diário automático não é gerado para esta brand.'),
        ),
        migrations.AddField(
            model_name='brand',
            name='scheduler_paused',
            field=models.BooleanField(default=False, help_text='Pausa temporária do scheduler (sem apagar configuração).'),
        ),
        migrations.AddField(
            model_name='brand',
            name='scheduler_timezone',
            field=models.CharField(blank=True, default='', help_text='Timezone IANA do scheduler desta brand. Vazio = usa o timezone da factory.', max_length=64),
        ),
        migrations.AddField(
            model_name='brand',
            name='start_jitter_minutes',
            field=models.PositiveSmallIntegerField(default=0, help_text='Jitter máximo aplicado ao início da janela (minutos).'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='long_slot_times',
            field=models.JSONField(blank=True, default=list, help_text='Legado: não usado pelo scheduler atual. Mantido para migração/histórico.'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='short_slot_times',
            field=models.JSONField(blank=True, default=list, help_text='Legado: não usado pelo scheduler atual. Mantido para migração/histórico.'),
        ),
        migrations.RunPython(backfill_scheduler_from_legacy_slots, noop_reverse),
    ]
