# Generated by Django 5.2.12 on 2026-04-03 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0033_brand_active_weekdays_brand_base_end_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='long_slot_times',
            field=models.JSONField(blank=True, default=list, help_text='Horários alvo para vídeos longos (lista de strings "HH:MM"). Com lista preenchida, o plano diário ancora longos nestes horários (± jitter) e distribui shorts nos intervalos livres.'),
        ),
    ]
