# Generated by Django 5.2.11 on 2026-09-03 11:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0035_brand_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='default_thumb_template_long',
            field=models.ForeignKey(blank=True, help_text='Modelo de capa padrão dos longs (asset THUMB_LONG desta marca).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='brands.brandasset'),
        ),
        migrations.AddField(
            model_name='brand',
            name='default_thumb_template_short',
            field=models.ForeignKey(blank=True, help_text='Modelo de capa padrão dos shorts (asset THUMB_SHORT desta marca).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='brands.brandasset'),
        ),
        migrations.AddField(
            model_name='brandasset',
            name='font',
            field=models.CharField(blank=True, choices=[('anton', 'Anton'), ('bebas', 'Bebas Neue'), ('montserrat', 'Montserrat ExtraBold'), ('impact', 'Impact')], default='', help_text='Fonte do texto. Vazio = fonte da marca.', max_length=20),
        ),
        migrations.AddField(
            model_name='brandasset',
            name='stroke_color',
            field=models.CharField(blank=True, default='', help_text='Cor do contorno (#RRGGBB). Vazio = cor da marca.', max_length=7),
        ),
        migrations.AddField(
            model_name='brandasset',
            name='stroke_enabled',
            field=models.BooleanField(default=False, help_text='Contorno no texto. Desligado por padrão: a arte do modelo já dá o contraste.'),
        ),
        migrations.AddField(
            model_name='brandasset',
            name='text_align',
            field=models.CharField(choices=[('left', 'Esquerda'), ('center', 'Centro'), ('right', 'Direita')], default='center', help_text='Alinhamento horizontal das linhas dentro da caixa.', max_length=6),
        ),
        migrations.AddField(
            model_name='brandasset',
            name='text_color',
            field=models.CharField(blank=True, default='', help_text='Cor do texto (#RRGGBB). Vazio = cor da marca.', max_length=7),
        ),
        migrations.AddField(
            model_name='brandasset',
            name='text_valign',
            field=models.CharField(choices=[('top', 'Topo'), ('middle', 'Meio'), ('bottom', 'Base')], default='middle', help_text='Onde o bloco de texto encosta na caixa.', max_length=6),
        ),
        migrations.AddField(
            model_name='brandasset',
            name='text_zone_h',
            field=models.PositiveSmallIntegerField(default=84, help_text='Altura da caixa de texto, em % da altura.'),
        ),
        migrations.AddField(
            model_name='brandasset',
            name='text_zone_w',
            field=models.PositiveSmallIntegerField(default=38, help_text='Largura da caixa de texto, em % da largura.'),
        ),
        migrations.AddField(
            model_name='brandasset',
            name='text_zone_x',
            field=models.PositiveSmallIntegerField(default=60, help_text='Borda esquerda da caixa de texto, em % da largura.'),
        ),
        migrations.AddField(
            model_name='brandasset',
            name='text_zone_y',
            field=models.PositiveSmallIntegerField(default=8, help_text='Topo da caixa de texto, em % da altura.'),
        ),
    ]
