# Generated by Django 5.2.11 on 2026-02-19 10:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuts', '0001_initial'),
        ('mediahub', '0002_sourcevideo_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cut',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='cuts/'),
        ),
        migrations.AddField(
            model_name='cut',
            name='format',
            field=models.CharField(choices=[('vertical', 'Vertical (9:16)'), ('horizontal', 'Horizontal (16:9)')], default='vertical', max_length=16),
        ),
        migrations.AddField(
            model_name='cut',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cuts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='cut',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cuts', to='mediahub.sourcevideo'),
        ),
    ]
