# Generated by Django 5.2.11 on 2026-02-19 11:07

from django.db import migrations, models


def tc_to_seconds(tc):
    if not tc or not isinstance(tc, str):
        return 0.0
    parts = [int(x) for x in tc.strip().split(":") if x.isdigit()]
    if not parts:
        return 0.0
    if len(parts) == 1:
        return float(parts[0])
    if len(parts) == 2:
        return float(parts[0] * 60 + parts[1])
    return float(parts[0] * 3600 + parts[1] * 60 + parts[2])


def populate_duration(apps, schema_editor):
    Cut = apps.get_model("cuts", "Cut")
    for cut in Cut.objects.filter(duration__isnull=True):
        try:
            dur = tc_to_seconds(cut.end_tc) - tc_to_seconds(cut.start_tc)
            cut.duration = max(0, dur)
            cut.save()
        except (ValueError, TypeError):
            pass


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('cuts', '0002_cut_file_cut_format_cut_user_alter_cut_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='cut',
            name='duration',
            field=models.FloatField(blank=True, help_text='Duração em segundos', null=True),
        ),
        migrations.RunPython(populate_duration, noop),
    ]
