# Generated by Django 5.2.11 on 2026-02-19 16:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0001_initial'),
        ('cuts', '0003_add_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='cut',
            name='brand',
            field=models.ForeignKey(blank=True, help_text='Marca para cortes de upload (cortes de source herdam da source)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cuts', to='brands.brand'),
        ),
    ]
