# Generated by Django 5.2.13 on 2026-05-18 11:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auto_cuts', '0033_alter_autocutsuggestion_theme_category'),
        ('brands', '0035_brand_category'),
        ('mediahub', '0002_sourcevideo_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MultipleCreatorJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=200)),
                ('source_kind', models.CharField(choices=[('FILE', 'Arquivo enviado'), ('SOURCE', 'SourceVideo existente'), ('YOUTUBE', 'URL YouTube')], max_length=10)),
                ('file', models.FileField(blank=True, max_length=255, null=True, upload_to='multiple_creator/sources/')),
                ('youtube_url', models.URLField(blank=True, default='', max_length=500)),
                ('assunto', models.CharField(blank=True, default='', max_length=300)),
                ('convidados', models.CharField(blank=True, default='', max_length=300)),
                ('prompt_version', models.CharField(blank=True, default='educational', max_length=64)),
                ('vertical_mode', models.CharField(blank=True, default='zoom_crop', max_length=32)),
                ('shorts_target', models.PositiveSmallIntegerField(default=12)),
                ('longs_target', models.PositiveSmallIntegerField(default=3)),
                ('thumbnail_font', models.CharField(blank=True, default='', max_length=64)),
                ('thumbnail_band_color', models.CharField(blank=True, default='', max_length=7)),
                ('thumbnail_text_color', models.CharField(blank=True, default='', max_length=7)),
                ('thumbnail_stroke_color', models.CharField(blank=True, default='', max_length=7)),
                ('transcript', models.TextField(blank=True, default='')),
                ('transcript_segments', models.JSONField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING_TRANSCRIPTION', 'Pendente - transcricao'), ('TRANSCRIBING', 'Transcrevendo'), ('READY', 'Pronto para fanout'), ('RUNNING_BRANDS', 'Processando brands'), ('DONE', 'Concluido'), ('PARTIAL', 'Concluido com falhas parciais'), ('ERROR', 'Erro')], default='PENDING_TRANSCRIPTION', max_length=30)),
                ('progress', models.PositiveSmallIntegerField(default=0)),
                ('progress_message', models.CharField(blank=True, default='', max_length=255)),
                ('error', models.TextField(blank=True, default='')),
                ('correlation_id', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='multiple_creator_jobs', to='mediahub.sourcevideo')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='multiple_creator_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MultipleCreatorBrandExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pendente'), ('ANALYZING', 'Analisando'), ('FINALIZING', 'Finalizando'), ('DONE', 'Concluido'), ('ERROR', 'Erro')], default='PENDING', max_length=20)),
                ('error', models.TextField(blank=True, default='')),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('auto_cut_analysis', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='multiple_creator_execution', to='auto_cuts.autocutanalysis')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='multiple_creator_executions', to='brands.brand')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brand_executions', to='multiple_creator.multiplecreatorjob')),
            ],
            options={
                'ordering': ['job_id', 'id'],
                'constraints': [models.UniqueConstraint(fields=('job', 'brand'), name='uniq_brand_per_mc_job')],
            },
        ),
    ]
