# Generated by Django 5.2.11 on 2026-02-25 19:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('brands', '0001_initial'),
        ('mediahub', '0002_sourcevideo_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AutoCutAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, help_text='Vídeo enviado diretamente (se não usar source)', null=True, upload_to='auto_cuts/sources/')),
                ('name', models.CharField(blank=True, default='', max_length=200)),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('transcribing', 'Transcrevendo'), ('analyzing', 'Analisando'), ('done', 'Concluído'), ('error', 'Erro')], default='pending', max_length=20)),
                ('progress', models.PositiveSmallIntegerField(default=0)),
                ('progress_message', models.CharField(blank=True, default='', max_length=200)),
                ('transcript', models.TextField(blank=True, default='')),
                ('transcript_segments', models.JSONField(blank=True, help_text='Segmentos Whisper [{start, end, text}]', null=True)),
                ('error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='auto_cut_analyses', to='brands.brand')),
                ('source', models.ForeignKey(blank=True, help_text='Source existente (opcional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auto_cut_analyses', to='mediahub.sourcevideo')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='auto_cut_analyses', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AutoCutSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cut_type', models.CharField(choices=[('short', 'Curto (Reels/TikTok/Shorts)'), ('long', 'Longo (YouTube)')], max_length=10)),
                ('start_tc', models.CharField(help_text='Ex: 12:34 ou 01:23:45', max_length=16)),
                ('end_tc', models.CharField(max_length=16)),
                ('title', models.CharField(blank=True, default='', max_length=200)),
                ('reason', models.TextField(blank=True, default='')),
                ('hook', models.CharField(blank=True, default='', max_length=500)),
                ('virality_score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('rank', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('duration_seconds', models.FloatField(blank=True, null=True)),
                ('duration_minutes', models.FloatField(blank=True, null=True)),
                ('raw_data', models.JSONField(blank=True, null=True)),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suggestions', to='auto_cuts.autocutanalysis')),
            ],
            options={
                'ordering': ['cut_type', 'rank', 'id'],
            },
        ),
    ]
