# Generated by Django 5.2.11 on 2026-02-25 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto_cuts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='autocutanalysis',
            name='assunto',
            field=models.CharField(blank=True, default='', help_text='Assunto/tema principal do vídeo', max_length=300),
        ),
        migrations.AddField(
            model_name='autocutanalysis',
            name='convidados',
            field=models.CharField(blank=True, default='', help_text='Nomes dos convidados separados por vírgula (ex: João, Maria, Pedro)', max_length=300),
        ),
    ]
