# Generated by Django 5.2.11 on 2026-02-25 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto_cuts', '0002_autocutanalysis_assunto_autocutanalysis_convidados'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autocutanalysis',
            name='file',
            field=models.FileField(blank=True, help_text='Vídeo enviado diretamente (se não usar source)', max_length=255, null=True, upload_to='auto_cuts/sources/'),
        ),
    ]
