# Generated by Django 5.2.11 on 2026-02-26 17:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto_cuts', '0003_file_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutoCutCorte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, help_text='Vídeo extraído (antes ou depois de queimar legenda)', max_length=255, null=True, upload_to='auto_cuts/cortes/')),
                ('format', models.CharField(choices=[('vertical', 'Vertical (9:16)'), ('horizontal', 'Horizontal (16:9)')], default='vertical', max_length=16)),
                ('needs_subtitle', models.BooleanField(default=False, help_text='Usuário marcou para incluir legenda')),
                ('user_wants_finalize', models.BooleanField(default=False, help_text='Usuário marcou para finalizar este corte')),
                ('is_finalized', models.BooleanField(default=False, help_text='Corte foi finalizado (legenda queimada ou vídeo pronto)')),
                ('subtitle_segments', models.JSONField(blank=True, help_text='Segmentos de legenda [{start, end, text}]', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cortes', to='auto_cuts.autocutanalysis')),
                ('suggestion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cortes', to='auto_cuts.autocutsuggestion')),
            ],
            options={
                'ordering': ['analysis', 'suggestion'],
            },
        ),
    ]
