# Generated by Django 5.2.11 on 2026-03-04 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto_cuts', '0007_add_english_prompt_versions'),
    ]

    operations = [
        migrations.AddField(
            model_name='autocutcorte',
            name='thumbnail',
            field=models.ImageField(blank=True, help_text='Thumbnail opcional para publicação no YouTube.', max_length=255, null=True, upload_to='auto_cuts/thumbnails/'),
        ),
    ]
