# Generated by Django 5.2.11 on 2026-03-06 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto_cuts', '0012_autocutanalysis_thumbnail_text_and_stroke_colors'),
    ]

    operations = [
        migrations.AddField(
            model_name='autocutsuggestion',
            name='source_asset_id',
            field=models.CharField(blank=True, default='', help_text='ID do vídeo original de origem (usado para diversidade de publicação).', max_length=120),
        ),
        migrations.AddField(
            model_name='autocutsuggestion',
            name='theme_category',
            field=models.CharField(blank=True, choices=[('BUSINESS_MONEY', 'Negócios / Dinheiro'), ('PSYCHOLOGY_RELATIONSHIPS', 'Psicologia / Relacionamentos'), ('STORIES_CURIOSITIES', 'Histórias e Curiosidades'), ('CONTROVERSIES_DEBATE', 'Polêmicas / Debate'), ('COMEDY_HUMOR', 'Comédia / Humor')], default='', help_text='Categoria temática retornada pela LLM (metadado obrigatório no novo fluxo).', max_length=40),
        ),
    ]
