# Generated by Django 5.2.12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto_cuts', '0015_add_viral_translate_prompt_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='autocutanalysis',
            name='distribution_mode',
            field=models.CharField(
                choices=[('theme', 'Por tema (IA)'), ('distribute', 'Distribuir pelas Brands')],
                default='theme',
                help_text="Quando target_brand vazio: 'theme' usa categoria da IA; 'distribute' envia para a brand com menos vídeos no banco.",
                max_length=20,
            ),
        ),
    ]
