# Generated by Django 5.2.12 on 2026-03-17 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto_cuts', '0024_autocutanalysis_distribution_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='autocutanalysis',
            name='is_ready_cuts',
            field=models.BooleanField(default=False, help_text='Vídeo(s) já editados: transcreve, LLM retorna só metadata (title, virality, thumbnail), finaliza. Sem extração de segmentos.'),
        ),
    ]
