# Generated by Django 5.2.12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto_cuts', '0025_add_is_ready_cuts'),
    ]

    operations = [
        migrations.AddField(
            model_name='autocutanalysis',
            name='vertical_mode',
            field=models.CharField(
                blank=True,
                choices=[('zoom_crop', 'Zoom e corte'), ('frame_center', 'Enquadrar e centralizar')],
                default='zoom_crop',
                help_text='Modo de reenquadramento vertical para shorts (16:9 → 9:16). Zoom preenche a tela; Enquadrar adiciona bordas e logo.',
                max_length=20,
            ),
        ),
    ]
