# Generated by Django 5.2.12 on 2026-04-05 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto_cuts', '0031_clear_orphan_long_overlay_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='autocutanalysis',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='autocutanalysis',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendente'), ('transcribing', 'Transcrevendo'), ('analyzing', 'Analisando'), ('finalizing', 'Finalizando'), ('done', 'Concluído'), ('error', 'Erro')], default='pending', max_length=20),
        ),
    ]
