# Generated by Django 5.2.12 on 2026-04-24 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto_cuts', '0032_autocutanalysis_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autocutsuggestion',
            name='theme_category',
            field=models.CharField(blank=True, default='', help_text='Code da BrandCategory (por factory) retornado pela LLM.', max_length=40),
        ),
    ]
