# Generated by Django 5.2.11 on 2026-09-03 11:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto_cuts', '0033_alter_autocutsuggestion_theme_category'),
        ('brands', '0036_brand_default_thumb_template_long_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='autocutanalysis',
            name='thumb_template_long',
            field=models.ForeignKey(blank=True, help_text='Modelo de capa dos longs (THUMB_LONG). Nulo = padrão da brand ou faixa inferior.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='brands.brandasset'),
        ),
        migrations.AddField(
            model_name='autocutanalysis',
            name='thumb_template_short',
            field=models.ForeignKey(blank=True, help_text='Modelo de capa dos shorts (THUMB_SHORT). Nulo = padrão da brand ou faixa inferior.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='brands.brandasset'),
        ),
    ]
